CREATE TABLE `schedule_cycles` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(36) NOT NULL,
  `shop_id` INTEGER NOT NULL,
  `name` VARCHAR(160) NOT NULL,
  `creation_method` VARCHAR(40) NOT NULL DEFAULT 'new',
  `mode` ENUM('TECH_SELF_FINAL', 'STORE_ASSIGN_FINAL') NOT NULL DEFAULT 'TECH_SELF_FINAL',
  `status` ENUM('DRAFT', 'RULE_SETTING', 'FINAL_CONFIRMING', 'COLLECTING_FEEDBACK', 'FEEDBACK_CLOSED', 'CONFIRMED', 'ACTIVE', 'CANCELLED', 'COMPLETED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT',
  `current_step` INTEGER NOT NULL DEFAULT 1,
  `template_type` ENUM('DAY', 'WEEK', 'MONTH') NOT NULL DEFAULT 'WEEK',
  `period_start` DATE NOT NULL,
  `period_end` DATE NOT NULL,
  `feedback_deadline` DATETIME(3) NULL,
  `template_matrix` JSON NOT NULL,
  `regular_holiday_weekdays` JSON NOT NULL,
  `rule_set` JSON NOT NULL,
  `auto_confirm_summary` JSON NULL,
  `launch_idempotency_key` VARCHAR(160) NULL,
  `auto_confirm_idempotency_key` VARCHAR(160) NULL,
  `finalize_idempotency_key` VARCHAR(160) NULL,
  `launched_at` DATETIME(3) NULL,
  `finalized_at` DATETIME(3) NULL,
  `active_at` DATETIME(3) NULL,
  `cancelled_at` DATETIME(3) NULL,
  `last_auto_confirm_at` DATETIME(3) NULL,
  `version` INTEGER NOT NULL DEFAULT 1,
  `created_by_id` INTEGER NOT NULL,
  `updated_by_id` INTEGER NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  `deleted_at` DATETIME(3) NULL,
  UNIQUE INDEX `schedule_cycles_public_id_key` (`public_id`),
  INDEX `schedule_cycles_shop_status_period_idx` (`shop_id`, `status`, `period_start`, `period_end`, `deleted_at`),
  INDEX `schedule_cycles_created_by_id_idx` (`created_by_id`),
  INDEX `schedule_cycles_updated_by_id_idx` (`updated_by_id`),
  INDEX `schedule_cycles_deleted_at_idx` (`deleted_at`),
  PRIMARY KEY (`id`),
  CONSTRAINT `schedule_cycles_shop_id_fkey` FOREIGN KEY (`shop_id`) REFERENCES `shops` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `schedule_cycle_targets` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `cycle_id` INTEGER NOT NULL,
  `technician_profile_id` INTEGER NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  `deleted_at` DATETIME(3) NULL,
  UNIQUE INDEX `schedule_cycle_targets_cycle_technician_key` (`cycle_id`, `technician_profile_id`),
  INDEX `schedule_cycle_targets_technician_deleted_idx` (`technician_profile_id`, `deleted_at`),
  INDEX `schedule_cycle_targets_deleted_at_idx` (`deleted_at`),
  PRIMARY KEY (`id`),
  CONSTRAINT `schedule_cycle_targets_cycle_id_fkey` FOREIGN KEY (`cycle_id`) REFERENCES `schedule_cycles` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `schedule_cycle_targets_technician_profile_id_fkey` FOREIGN KEY (`technician_profile_id`) REFERENCES `technician_profiles` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `schedule_cycle_feedbacks` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `cycle_id` INTEGER NOT NULL,
  `technician_profile_id` INTEGER NOT NULL,
  `date` DATE NOT NULL,
  `hour` INTEGER NOT NULL,
  `status` ENUM('AVAILABLE', 'UNAVAILABLE', 'UPDATED') NOT NULL,
  `note` VARCHAR(500) NOT NULL DEFAULT '',
  `submitted_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  `deleted_at` DATETIME(3) NULL,
  UNIQUE INDEX `schedule_cycle_feedbacks_cycle_technician_date_hour_key` (`cycle_id`, `technician_profile_id`, `date`, `hour`),
  INDEX `schedule_cycle_feedbacks_technician_submitted_idx` (`technician_profile_id`, `submitted_at`, `deleted_at`),
  INDEX `schedule_cycle_feedbacks_cycle_slot_status_idx` (`cycle_id`, `date`, `hour`, `status`, `deleted_at`),
  INDEX `schedule_cycle_feedbacks_deleted_at_idx` (`deleted_at`),
  PRIMARY KEY (`id`),
  CONSTRAINT `schedule_cycle_feedbacks_cycle_id_fkey` FOREIGN KEY (`cycle_id`) REFERENCES `schedule_cycles` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `schedule_cycle_feedbacks_technician_profile_id_fkey` FOREIGN KEY (`technician_profile_id`) REFERENCES `technician_profiles` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `schedule_cycle_final_shifts` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `cycle_id` INTEGER NOT NULL,
  `technician_profile_id` INTEGER NOT NULL,
  `availability_id` INTEGER NULL,
  `date` DATE NOT NULL,
  `hour` INTEGER NOT NULL,
  `status` ENUM('CONFIRMED', 'WAITLISTED', 'CANCELLED') NOT NULL,
  `source` ENUM('AUTO', 'MANUAL') NOT NULL DEFAULT 'AUTO',
  `rule_snapshot` JSON NOT NULL,
  `confirmed_at` DATETIME(3) NOT NULL,
  `confirmed_by_id` INTEGER NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  `deleted_at` DATETIME(3) NULL,
  UNIQUE INDEX `schedule_cycle_final_shifts_cycle_technician_date_hour_key` (`cycle_id`, `technician_profile_id`, `date`, `hour`),
  INDEX `schedule_cycle_final_shifts_technician_slot_idx` (`technician_profile_id`, `date`, `hour`, `status`, `deleted_at`),
  INDEX `schedule_cycle_final_shifts_cycle_status_idx` (`cycle_id`, `status`, `deleted_at`),
  INDEX `schedule_cycle_final_shifts_availability_id_idx` (`availability_id`),
  INDEX `schedule_cycle_final_shifts_confirmed_by_id_idx` (`confirmed_by_id`),
  INDEX `schedule_cycle_final_shifts_deleted_at_idx` (`deleted_at`),
  PRIMARY KEY (`id`),
  CONSTRAINT `schedule_cycle_final_shifts_cycle_id_fkey` FOREIGN KEY (`cycle_id`) REFERENCES `schedule_cycles` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `schedule_cycle_final_shifts_technician_profile_id_fkey` FOREIGN KEY (`technician_profile_id`) REFERENCES `technician_profiles` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `schedule_cycle_final_shifts_availability_id_fkey` FOREIGN KEY (`availability_id`) REFERENCES `availabilities` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
