import type { Language } from "../../i18n/translations";

const translations: Record<string, [string, string, string]> = {
  "需求中心": ["需求中心", "需要センター", "Demand center"],
  "情报中心": ["情报中心", "情報センター", "Information center"],
  "查看正式发布、响应、匹配、请求费与审计记录。": ["查看正式发布、响应、匹配、请求费与审计记录。", "正式な投稿、応募、マッチング、リクエスト料、監査記録を確認します。", "Review persisted posts, claims, matching, request fees, and audit records."],
  "只读": ["只读", "読み取り専用", "Read only"],
  "关键词": ["关键词", "キーワード", "Keyword"],
  "搜索标题、内容、地区或发布者": ["搜索标题、内容、地区或发布者", "タイトル、内容、地域、投稿者を検索", "Search title, content, area, or publisher"],
  "状态": ["状态", "ステータス", "Status"],
  "全部状态": ["全部状态", "すべてのステータス", "All statuses"],
  "匹配方式": ["匹配方式", "マッチング方式", "Match mode"],
  "全部方式": ["全部方式", "すべての方式", "All modes"],
  "快速匹配": ["快速匹配", "クイックマッチ", "Quick match"],
  "选择匹配": ["选择匹配", "選択マッチ", "Selective match"],
  "发布者身份": ["发布者身份", "投稿者の身分", "Publisher identity"],
  "搜索": ["搜索", "検索", "Search"],
  "重置": ["重置", "リセット", "Reset"],
  "加载中…": ["加载中…", "読み込み中…", "Loading…"],
  "正式数据加载失败": ["正式数据加载失败", "正式データの読み込みに失敗しました", "Failed to load persisted data"],
  "重试": ["重试", "再試行", "Retry"],
  "暂无符合条件的正式记录": ["暂无符合条件的正式记录", "条件に一致する正式記録はありません", "No persisted records match the filters"],
  "服务器共 {total} 条，第 {page} / {pages} 页": ["服务器共 {total} 条，第 {page} / {pages} 页", "サーバー全 {total} 件、{page} / {pages} ページ", "{total} server records, page {page} / {pages}"],
  "上一页": ["上一页", "前へ", "Previous"],
  "下一页": ["下一页", "次へ", "Next"],
  "标题": ["标题", "タイトル", "Title"],
  "服务范围": ["服务范围", "サービス範囲", "Service scope"],
  "预算": ["预算", "予算", "Budget"],
  "到期": ["到期", "期限", "Expires"],
  "响应": ["响应", "応募", "Claims"],
  "匹配": ["匹配", "マッチング", "Matching"],
  "请求费": ["请求费", "リクエスト料", "Request fee"],
  "查看详情": ["查看详情", "詳細を見る", "View details"],
  "详情": ["详情", "詳細", "Detail"],
  "基础信息": ["基础信息", "基本情報", "Basic information"],
  "类型": ["类型", "種別", "Type"],
  "发布者": ["发布者", "投稿者", "Publisher"],
  "发布时间": ["发布时间", "投稿日", "Published"],
  "服务时间": ["服务时间", "サービス時間", "Service time"],
  "地区": ["地区", "地域", "Area"],
  "正文": ["正文", "本文", "Content"],
  "请求参数": ["请求参数", "リクエスト条件", "Request parameters"],
  "目标人数": ["目标人数", "募集人数", "Target providers"],
  "额度快照": ["额度快照", "上限スナップショット", "Capacity snapshot"],
  "预算方式": ["预算方式", "予算方式", "Budget mode"],
  "请求费状态": ["请求费状态", "リクエスト料状態", "Request fee status"],
  "冻结": ["冻结", "保留", "Held"],
  "已扣取": ["已扣取", "回収済み", "Captured"],
  "已释放": ["已释放", "解放済み", "Released"],
  "无请求费记录": ["无请求费记录", "リクエスト料記録なし", "No request fee record"],
  "抢单响应": ["抢单响应", "応募一覧", "Claims"],
  "暂无响应": ["暂无响应", "応募はありません", "No claims"],
  "匹配结果": ["匹配结果", "マッチング結果", "Matching result"],
  "暂无匹配记录": ["暂无匹配记录", "マッチング記録はありません", "No matching record"],
  "审计时间线": ["审计时间线", "監査タイムライン", "Audit timeline"],
  "暂无时间线事件": ["暂无时间线事件", "タイムラインイベントはありません", "No timeline events"],
  "详情加载失败": ["详情加载失败", "詳細の読み込みに失敗しました", "Failed to load detail"],
  "发布中": ["发布中", "公開中", "Published"],
  "已匹配": ["已匹配", "マッチ済み", "Matched"],
  "已过期": ["已过期", "期限切れ", "Expired"],
  "已撤回": ["已撤回", "取り下げ済み", "Withdrawn"],
  "已关闭": ["已关闭", "終了", "Closed"],
  "需求": ["需求", "需要", "Demand"],
  "情报": ["情报", "情報", "Information"],
  "未设置": ["未设置", "未設定", "Not set"]
};

export const exchangeOperationsText = (
  source: string,
  language: Language,
  values: Record<string, string | number> = {}
): string => {
  const item = translations[source];
  const index = language === "ja" ? 1 : language === "en" ? 2 : 0;
  return (item?.[index] ?? source).replace(/\{(\w+)\}/g, (_match, key: string) => String(values[key] ?? ""));
};
