import { type Language, translateText } from "../../i18n/translations";

type ImUiTranslation = Partial<Record<Exclude<Language, "zh">, string>>;

const imUiTranslations: Record<string, ImUiTranslation> = {
  查看聊天记录: {
    "zh-Hant": "查看聊天記錄",
    ja: "チャット履歴を表示",
    en: "View chat record",
    ko: "채팅 기록 보기",
  },
  关闭聊天记录: {
    "zh-Hant": "關閉聊天記錄",
    ja: "チャット履歴を閉じる",
    en: "Close chat record",
    ko: "채팅 기록 닫기",
  },
  聊天记录说明: {
    "zh-Hant": "聊天記錄說明",
    ja: "チャット履歴の説明",
    en: "About this chat record",
    ko: "채팅 기록 안내",
  },
  "此页面展示创建时保存的只读消息快照，不会随原聊天资料变化。": {
    "zh-Hant": "此頁面顯示建立時儲存的唯讀訊息快照，不會隨原聊天資料變更。",
    ja: "このページには作成時に保存された読み取り専用のメッセージスナップショットが表示され、元のチャット情報が変わっても更新されません。",
    en: "This page shows a read-only message snapshot saved when the record was created. It does not change with the original chat.",
    ko: "이 페이지에는 기록 생성 시 저장된 읽기 전용 메시지 스냅샷이 표시되며 원본 채팅 정보가 바뀌어도 변경되지 않습니다.",
  },
  聊天记录媒体: {
    "zh-Hant": "聊天記錄媒體",
    ja: "チャット履歴のメディア",
    en: "Chat record media",
    ko: "채팅 기록 미디어",
  },
  媒体不可用: {
    "zh-Hant": "媒體不可用",
    ja: "メディアを利用できません",
    en: "Media unavailable",
    ko: "미디어를 사용할 수 없습니다",
  },
  媒体读取失败: {
    "zh-Hant": "媒體讀取失敗",
    ja: "メディアを読み込めませんでした",
    en: "Couldn't load media",
    ko: "미디어를 불러오지 못했습니다",
  },
  正在读取媒体: {
    "zh-Hant": "正在讀取媒體",
    ja: "メディアを読み込んでいます",
    en: "Loading media",
    ko: "미디어를 불러오는 중",
  },
  正在读取聊天记录: {
    "zh-Hant": "正在讀取聊天記錄",
    ja: "チャット履歴を読み込んでいます",
    en: "Loading chat record",
    ko: "채팅 기록을 불러오는 중",
  },
  加载更早: {
    "zh-Hant": "載入更早訊息",
    ja: "以前のメッセージを読み込む",
    en: "Load earlier",
    ko: "이전 메시지 불러오기",
  },
  正在加载: {
    "zh-Hant": "正在載入",
    ja: "読み込み中",
    en: "Loading",
    ko: "불러오는 중",
  },
  返回个人中心: {
    "zh-Hant": "返回個人中心",
    ja: "マイページに戻る",
    en: "Back to profile",
    ko: "마이페이지로 돌아가기",
  },
  我的收藏: {
    "zh-Hant": "我的收藏",
    ja: "お気に入り",
    en: "My favorites",
    ko: "내 즐겨찾기",
  },
  搜索收藏: {
    "zh-Hant": "搜尋收藏",
    ja: "お気に入りを検索",
    en: "Search favorites",
    ko: "즐겨찾기 검색",
  },
  搜索收藏内容: {
    "zh-Hant": "搜尋收藏內容",
    ja: "お気に入りを検索",
    en: "Search saved items",
    ko: "즐겨찾기 내용 검색",
  },
  关闭收藏: {
    "zh-Hant": "關閉收藏",
    ja: "お気に入りを閉じる",
    en: "Close favorites",
    ko: "즐겨찾기 닫기",
  },
  "店铺、技师、服务、动态与聊天记录": {
    "zh-Hant": "店鋪、技師、服務、動態與聊天記錄",
    ja: "店舗、スタッフ、サービス、投稿、チャット履歴",
    en: "Shops, technicians, services, posts, and chat records",
    ko: "매장, 스태프, 서비스, 게시물 및 채팅 기록",
  },
  店铺: { "zh-Hant": "店鋪", ja: "店舗", en: "Shops", ko: "매장" },
  技师: { "zh-Hant": "技師", ja: "スタッフ", en: "Technicians", ko: "스태프" },
  服务: { "zh-Hant": "服務", ja: "サービス", en: "Services", ko: "서비스" },
  动态: { "zh-Hant": "動態", ja: "投稿", en: "Posts", ko: "게시물" },
  暂无收藏的店铺: {
    "zh-Hant": "暫無收藏的店鋪",
    ja: "お気に入りの店舗はありません",
    en: "No favorite shops yet",
    ko: "즐겨찾기한 매장이 없습니다",
  },
  暂无收藏的技师: {
    "zh-Hant": "暫無收藏的技師",
    ja: "お気に入りのスタッフはいません",
    en: "No favorite technicians yet",
    ko: "즐겨찾기한 스태프가 없습니다",
  },
  暂无收藏的服务: {
    "zh-Hant": "暫無收藏的服務",
    ja: "お気に入りのサービスはありません",
    en: "No favorite services yet",
    ko: "즐겨찾기한 서비스가 없습니다",
  },
  暂无收藏的动态: {
    "zh-Hant": "暫無收藏的動態",
    ja: "お気に入りの投稿はありません",
    en: "No favorite posts yet",
    ko: "즐겨찾기한 게시물이 없습니다",
  },
  "移除收藏失败，请重试": {
    "zh-Hant": "移除收藏失敗，請再試一次",
    ja: "お気に入りの削除に失敗しました。もう一度お試しください",
    en: "Could not remove this favorite. Try again",
    ko: "즐겨찾기를 삭제하지 못했습니다. 다시 시도해 주세요",
  },
  当前页没有匹配的聊天记录: {
    "zh-Hant": "目前頁面沒有相符的聊天記錄",
    ja: "現在のページに一致するチャット履歴はありません",
    en: "No matching chat records on this page",
    ko: "현재 페이지에 일치하는 채팅 기록이 없습니다",
  },
  动态收藏: {
    "zh-Hant": "動態收藏",
    ja: "お気に入りの投稿",
    en: "Bookmarked posts",
    ko: "즐겨찾기 게시물",
  },
  保存的聊天记录: {
    "zh-Hant": "已儲存的聊天記錄",
    ja: "お気に入りのチャット履歴",
    en: "Saved chat records",
    ko: "저장된 채팅 기록",
  },
  保存的服务与名片: {
    "zh-Hant": "已儲存的服務與名片",
    ja: "お気に入りのサービス・カード",
    en: "Saved services and cards",
    ko: "저장된 서비스와 카드",
  },
  "服务、店铺与技师": {
    "zh-Hant": "服務、店鋪與技師",
    ja: "サービス・店舗・技術者",
    en: "Services, shops and technicians",
    ko: "서비스, 매장 및 기술자",
  },
  暂无收藏的服务或名片: {
    "zh-Hant": "暫無收藏的服務或名片",
    ja: "お気に入りのサービスやカードはありません",
    en: "No favorite services or cards yet",
    ko: "즐겨찾기한 서비스나 카드가 없습니다",
  },
  正在读取收藏: {
    "zh-Hant": "正在讀取收藏",
    ja: "お気に入りを読み込んでいます",
    en: "Loading favorites",
    ko: "즐겨찾기를 불러오는 중",
  },
  收藏读取失败: {
    "zh-Hant": "收藏讀取失敗",
    ja: "お気に入りを読み込めませんでした",
    en: "Couldn't load favorites",
    ko: "즐겨찾기를 불러오지 못했습니다",
  },
  "收藏失败，请稍后重试": {
    "zh-Hant": "收藏失敗，請稍後再試",
    ja: "お気に入りに追加できませんでした。しばらくしてからもう一度お試しください。",
    en: "Couldn't add to favorites. Try again later.",
    ko: "즐겨찾기에 추가하지 못했습니다. 잠시 후 다시 시도하세요",
  },
  暂无收藏的聊天记录: {
    "zh-Hant": "暫無收藏的聊天記錄",
    ja: "お気に入りのチャット履歴はありません",
    en: "No favorite chat records yet",
    ko: "즐겨찾기한 채팅 기록이 없습니다",
  },
  移除失败: {
    "zh-Hant": "移除失敗",
    ja: "削除できませんでした",
    en: "Couldn't remove favorite",
    ko: "즐겨찾기를 삭제하지 못했습니다",
  },
  正在移除: {
    "zh-Hant": "正在移除",
    ja: "削除中",
    en: "Removing",
    ko: "삭제 중",
  },
  移除收藏: {
    "zh-Hant": "移除收藏",
    ja: "お気に入りから削除",
    en: "Remove favorite",
    ko: "즐겨찾기에서 삭제",
  },
  收藏分页: {
    "zh-Hant": "收藏分頁",
    ja: "お気に入りのページ",
    en: "Favorites pages",
    ko: "즐겨찾기 페이지",
  },
  上一页: {
    "zh-Hant": "上一頁",
    ja: "前のページ",
    en: "Previous page",
    ko: "이전 페이지",
  },
  下一页: {
    "zh-Hant": "下一頁",
    ja: "次のページ",
    en: "Next page",
    ko: "다음 페이지",
  },
  重试: { "zh-Hant": "重試", ja: "再試行", en: "Retry", ko: "다시 시도" },
  暂无服务号: {
    "zh-Hant": "暫無服務號",
    ja: "サービスアカウントはありません",
    en: "No service accounts",
    ko: "서비스 계정이 없습니다",
  },
  "正式服务号能力尚未接入，当前没有可展示的服务号。": {
    "zh-Hant": "正式服務號功能尚未接入，目前沒有可顯示的服務號。",
    ja: "正式なサービスアカウント機能はまだ接続されていないため、現在表示できるサービスアカウントはありません。",
    en: "Formal service accounts are not connected yet, so there are no service accounts to display.",
    ko: "정식 서비스 계정 기능이 아직 연결되지 않아 현재 표시할 서비스 계정이 없습니다.",
  },
  服务号加载失败: {
    "zh-Hant": "服務號載入失敗",
    ja: "サービスアカウントを読み込めませんでした",
    en: "Couldn't load service accounts",
    ko: "서비스 계정을 불러오지 못했습니다",
  },
  "请稍后重试。": {
    "zh-Hant": "請稍後再試。",
    ja: "しばらくしてからもう一度お試しください。",
    en: "Please try again later.",
    ko: "잠시 후 다시 시도해 주세요.",
  },
  正在加载服务号: {
    "zh-Hant": "正在載入服務號",
    ja: "サービスアカウントを読み込んでいます",
    en: "Loading service accounts",
    ko: "서비스 계정을 불러오는 중",
  },
  "请稍候。": {
    "zh-Hant": "請稍候。",
    ja: "しばらくお待ちください。",
    en: "Please wait.",
    ko: "잠시만 기다려 주세요.",
  },
  翻译: { "zh-Hant": "翻譯", ja: "翻訳", en: "Translate", ko: "번역" },
  隐藏译文: {
    "zh-Hant": "隱藏譯文",
    ja: "翻訳を非表示",
    en: "Hide translation",
    ko: "번역 숨기기",
  },
  多选: {
    "zh-Hant": "多選",
    ja: "複数選択",
    en: "Select multiple",
    ko: "여러 개 선택",
  },
  "已选择 {count} 条信息": {
    "zh-Hant": "已選擇 {count} 則訊息",
    ja: "{count}件のメッセージを選択済み",
    en: "{count} messages selected",
    ko: "메시지 {count}개 선택됨",
  },
  选择到这里: {
    "zh-Hant": "選擇到這裡",
    ja: "ここまで",
    en: "Select to here",
    ko: "여기까지 선택",
  },
  转发: { "zh-Hant": "轉發", ja: "シェア", en: "Forward", ko: "전달" },
  复制: { "zh-Hant": "複製", ja: "コピー", en: "Copy", ko: "복사" },
  收藏: { "zh-Hant": "收藏", ja: "お気に入り", en: "Favorite", ko: "즐겨찾기" },
  删除: { "zh-Hant": "刪除", ja: "削除", en: "Delete", ko: "삭제" },
  聊天记录: {
    "zh-Hant": "聊天記錄",
    ja: "チャット履歴",
    en: "Chat history",
    ko: "채팅 기록",
  },
  最多选择100条信息: {
    "zh-Hant": "最多選擇100則訊息",
    ja: "メッセージは最大100件まで選択できます",
    en: "You can select up to 100 messages",
    ko: "메시지는 최대 100개까지 선택할 수 있습니다",
  },
  本月免费翻译额度已用完: {
    "zh-Hant": "本月免費翻譯額度已用完",
    ja: "今月の無料翻訳上限に達しました",
    en: "This month's free translation quota has been used up",
    ko: "이번 달 무료 번역 한도를 모두 사용했습니다",
  },
  "翻译请求较多，请稍后重试": {
    "zh-Hant": "翻譯請求較多，請稍後再試",
    ja: "翻訳リクエストが多すぎます。しばらくしてからもう一度お試しください",
    en: "Too many translation requests. Try again later.",
    ko: "번역 요청이 많습니다. 잠시 후 다시 시도해 주세요",
  },
  "翻译服务暂不可用，请稍后重试": {
    "zh-Hant": "翻譯服務暫不可用，請稍後再試",
    ja: "翻訳サービスを一時的に利用できません。しばらくしてからもう一度お試しください",
    en: "Translation service is temporarily unavailable. Try again later.",
    ko: "번역 서비스를 일시적으로 사용할 수 없습니다. 잠시 후 다시 시도해 주세요",
  },
  "翻译失败，请稍后重试": {
    "zh-Hant": "翻譯失敗，請稍後再試",
    ja: "翻訳に失敗しました。しばらくしてからもう一度お試しください",
    en: "Translation failed. Try again later.",
    ko: "번역에 실패했습니다. 잠시 후 다시 시도해 주세요",
  },
  当前内容无需翻译: {
    "zh-Hant": "目前內容無需翻譯",
    ja: "この内容は翻訳する必要がありません",
    en: "This content doesn't need translation",
    ko: "이 콘텐츠는 번역할 필요가 없습니다",
  },
  此消息不支持翻译: {
    "zh-Hant": "此訊息不支援翻譯",
    ja: "このメッセージは翻訳できません",
    en: "This message can't be translated",
    ko: "이 메시지는 번역할 수 없습니다",
  },
  所选信息包含暂不支持转发或收藏的类型: {
    "zh-Hant": "所選訊息包含目前無法轉發或收藏的類型",
    ja: "選択したメッセージに転送またはお気に入り登録できない形式が含まれています",
    en: "Some selected messages can't be forwarded or favorited",
    ko: "선택한 메시지에 전달하거나 즐겨찾기할 수 없는 형식이 포함되어 있습니다",
  },
  "将从你的聊天记录中删除 {count} 条信息，不影响对方。": {
    "zh-Hant": "將從你的聊天記錄中刪除 {count} 則訊息，不影響對方。",
    ja: "チャット履歴から{count}件のメッセージを削除します。相手側には影響しません。",
    en: "Delete {count} messages from your chat history. This won't affect the other person.",
    ko: "채팅 기록에서 메시지 {count}개를 삭제합니다. 상대방에게는 영향을 주지 않습니다.",
  },
  聊天记录不可用: {
    "zh-Hant": "聊天記錄不可用",
    ja: "チャット履歴を利用できません",
    en: "Chat record unavailable",
    ko: "채팅 기록을 사용할 수 없습니다",
  },
  "转发内容已失效，请重新选择": {
    "zh-Hant": "轉發內容已失效，請重新選擇",
    ja: "シェアする内容の有効期限が切れました。もう一度選択してください",
    en: "Forwarding selection expired. Select the messages again.",
    ko: "전달할 내용이 만료되었습니다. 다시 선택해 주세요",
  },
};

export function translateImUiText(source: string, language: Language): string {
  if (language === "zh") return source;
  return (
    imUiTranslations[source]?.[language] ?? translateText(source, language)
  );
}
